spring.application.name=CURRENCY-EXCHANGE
#server.port=0
spring.config.import=optional:configserver:http://localhost:8888

# Configuration for MySQL Database
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url = jdbc:mysql://localhost:3306/mustafeez
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true
#Load balancing :https://chatgpt.com/c/6a0dcd2d-0014-8321-9742-a344cc8be277
#Eureka server registry
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#resilience4j.retry.instances.sample-api.maxAttempts=5 #NEW
#resilience4j.retry.instances.sample-api.maxRetryAttempts=5 #OLD
#Resilience4j with Spring Boot 4
https://chatgpt.com/c/6a2a7e82-a7b0-83a2-99fa-4fc1220987b4